### ISSUE TITLE
Issues and suggested fix in code

### ISSUE THREAD

**Issue by baehaeli** [Sowmya-R-Krishnan/RSAPred#3]
I encountered some issues when running the code. 

### Issue1
  **Error:**
![image](https://github.com/Sowmya-R-Krishnan/RSAPred/assets/11719464/b23e7787-7096-47fa-9a5d-b83e6f17978a)
  
  I can fix this issue by chainging the code
  
  **Original code:**
  https://github.com/Sowmya-R-Krishnan/RSAPred/blob/03fbc3fb9600986f2680ab1bffe01630a4a5d35d/Feature_selection/ffs_final.py#L92
  
  **Fixed code:**
  `models = [(list(combo), results[i][1]) for i, combo in enumerate(feat_combinations_pass)]
  `
### Issue2
  **Error:**
![image](https://github.com/Sowmya-R-Krishnan/RSAPred/assets/11719464/fcd806cd-86ca-4d3a-900d-f712f03219a9)

  **Original code:**
https://github.com/Sowmya-R-Krishnan/RSAPred/blob/03fbc3fb9600986f2680ab1bffe01630a4a5d35d/Feature_selection/process_regression_output_v2.py#L24

  **Fixed code:**
 `best_models = df2.loc[df2[least_featnum]>min_model_metric]
  `

I believe this fix will help others who encounter the same issue.

**Comment by Sowmya-R-Krishnan** [comment]
Hi. Thanks for the suggestions. If possible, can you share the output files you got from the n_feat=2 run? I will check the suggested fixes once in my system and update the same in the repo.

**Comment by baehaeli** [comment]
These are the files I obtained from running the code applying the aforementioned fixes.
[outputs.zip](https://github.com/Sowmya-R-Krishnan/RSAPred/files/15412952/outputs.zip)

I follow the sample commands.

Data processing : 
python calc_kmer_composition_features_v1.py "./data/rna_data.csv" "./sample_output/"
python calc_ppseudoDNC_features_v1.py "./data/rna_data.csv" "./data/Physicochemical_indices_RNA.csv" "./sample_output/"
python calc_triplet_str_composition_features_v1.py "./data/rna_data.csv" "./sample_output/"
python calc_pseudo_structure_composition_v1.py "./data/rna_data.csv" "./sample_output/"
obabel -ismi ./data/mol_data.smi -osdf -O ./sample_output/mol_data.sdf --gen3d -h
python -m mordred ./sample_output/mol_data.sdf -t sdf -o ./sample_output/Mol_features_v1.csv -3
python combine_RNA_features_v1.py "./sample_output/Mononucleotide_v1.out" "./sample_output/Dinucleotide_v1.out" "./sample_output/Trinucleotide_v1.out" "./sample_output/Tetranucleotide_v1.out" "./sample_output/pPseudoDNC_features_v1.out" "./sample_output/Triplet_features_v1.out" "./sample_output/Pseudo_structure_status_composition_v1.out" "./sample_output/RNA_features_v1.csv"
python create_dataset_v1.py "./sample_output/RNA_features_v1.csv" "./sample_output/Mol_features_v1.csv" "./data/sample_data.csv" "./sample_output/Final_sample_dataset_v1.csv"
 
Feature selection : 
python -u ffs_final.py "./data/Final_sample_dataset_v1.csv" "./data/Pairwise_featcorr_0.8.pkl" 3 2 "all" './output/'
python -u process_regression_output_v1.py './output/Aptamers_best_2_feature_combos.log' "pass_models.log" "best_models.log"
python -u get_desc_stats_v1.py "best_models.log" 2 "feat_stats.out" "feat_pass.out"
python -u process_regression_output_v2.py "best_models.log" "best_models.log" 2 "prev_vs_current_best_models.log"

**Comment by Sowmya-R-Krishnan** [comment]
Hi. Thanks for sharing the commands and output files. As replied to your other issue, changing the cut-off value in process_regression_output.py is sufficient to execute the codes without any errors. Upon checking with cut-off value of 0.3 (instead of the default value provided), I could get the results file without issues. So, closing this issue here.

```
(dgl_env) sowmya@XXX:~/.../$ python process_regression_output_v1.py "./output_aptamer/Feature_selection_output_aptamer/Aptamers_best_2_feature_combos.log" "2feat_pass_models.log" "2feat_best_models.log"
9815 7210
Regression output processed.
```
