### ISSUE TITLE
Cannot find file best_model.log

### ISSUE THREAD

**Issue by DoraemonXia** [Sowmya-R-Krishnan/RSAPred#4]
Hello, I didn't find the file named "best_model.log", could you please tell me where is it ?

**Comment by Sowmya-R-Krishnan** [comment]
Hi, Thanks for the message. Best_model.log is the output file generated by the **process_regression_output_v1.py** script. The codes have to be run in the order as specified in this [README](https://github.com/Sowmya-R-Krishnan/RSAPred/blob/main/Feature_selection/README.md) file. Hope this clarifies.
